### ISSUE TITLE
Possible bug with  AMQP.Queue.purge/2

### ISSUE THREAD

**Issue by lessless** [pma/amqp#141]
Hi folks,

There is a chance that  `AMQP.Queue.purge` is working properly.

Given this code

```
defmodule TestApp.AMQPClient do
  def cleanup_queue() do
    {:ok, conn} = AMQP.Connection.open() |> IO.inspect
    {:ok, chan} = AMQP.Channel.open(conn) |> IO.inspect
    {:ok, queue} = AMQP.Queue.declare(chan, "apples_queue", durable: true) |> IO.inspect
    AMQP.Queue.purge(chan, queue)  |> IO.inspect
    AMQP.Channel.close(chan) |> IO.inspect
    AMQP.Connection.close(conn)  |> IO.inspect
  end
end
```

when I call it  there is the following error

```
Interactive Elixir (1.9.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> TestApp.AMQPClient.cleanup_queue()
{:ok, %AMQP.Connection{pid: #PID<0.338.0>}}
{:ok,
 %AMQP.Channel{conn: %AMQP.Connection{pid: #PID<0.338.0>}, pid: #PID<0.347.0>}}
{:ok,
 %{consumer_count: 1, message_count: 0, queue: "apples_queue"}}
** (exit) exited in: :gen_server.call(#PID<0.347.0>, {:call, {:"queue.purge", 0, %{consumer_count: 1, message_count: 0, queue: "apples_queue"}, false}, :none, #PID<0.316.0>}, 60000)
    ** (EXIT) shutdown
    (stdlib) gen_server.erl:223: :gen_server.call/3
    (amqp) lib/amqp/queue.ex:102: AMQP.Queue.purge/2
    (test_app) test/support/amqp_client.ex:6: TestApp.AMQPClient.cleanup_queue/0
iex(1)> 17:21:13.393 [error] CRASH REPORT Process <0.348.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(#{consumer_count => 1,message_count => 0,queue => <<"apples_queue">>}) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185
17:21:13.393 [error] Supervisor {<0.345.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.8>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.347.0>, {<<"client 127.0.0.1:56756 -> 127.0.0.1:5672">>,1}) at <0.348.0> exit with reason bad argument in call to erlang:size(#{consumer_count => 1,message_count => 0,queue => <<"apples_queue">>}) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185 in context child_terminated
17:21:13.393 [error] Supervisor {<0.345.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.8>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.347.0>, {<<"client 127.0.0.1:56756 -> 127.0.0.1:5672">>,1}) at <0.348.0> exit with reason reached_max_restart_intensity in context shutdown
```

Can anyone reproduce it?

**Comment by ono** [comment]
`Queue.declare/3` returns `{:ok, map()}`.
https://github.com/pma/amqp/blob/master/lib/amqp/queue.ex#L39

So can you try this?

```elixir
{:ok, %{queue: queue}} = AMQP.Queue.declare(chan, "apples_queue", durable: true)
```

Hope it solves the issue.
