### ISSUE TITLE
Cannot declare Exchange of different type from plugin

### ISSUE THREAD

**Issue by bbtdev** [pma/amqp#170]
Hi,

This maybe not an issue, but a cry for help :).

I am trying to use the " RabbitMQ Delayed Message Plugin" and in the documentation it says

```
To use the Delayed Message Exchange you just need to declare an exchange providing the "x-delayed-message" exchange type as follows:
// ... elided code ...
Map<String, Object> args = new HashMap<String, Object>();
args.put("x-delayed-type", "direct");
channel.exchangeDeclare("my-exchange", "x-delayed-message", true, false, args);
// ... more code ...
```

So in elixir I am doing:
    `AMQP.Exchange.declare(chan, "test_exchange", :"x-delayed-message", ["x-delayed-type": "direct"])`
and other variations.
And I am getting:
```
** (exit) exited in: :gen_server.call(#PID<0.307.0>, {:call, {:"exchange.declare", 0, "test_exchange", "x-delayed-message", false, false, false, false, false, []}, :none, #PID<0.292.0>}, 60000)
    ** (EXIT) shutdown: {:server_initiated_close, 406, "PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'test_exchange' in vhost '/': received ''x-delayed-message'' but current is 'direct'"}
    (stdlib 3.13) gen_server.erl:246: :gen_server.call/3
    (amqp 1.4.2) lib/amqp/exchange.ex:48: AMQP.Exchange.declare/4
    (testing 0.1.0) lib/testing.ex:29: Testing.rabbit/0
```

Any advice?

**Comment by ono** [comment]
I am not familiar with the plugin but suggest you to try:

```elixir
args = [
  {"x-delayed-type", :longstr, "direct"}
]
AMQP.Exchange.declare(chan, "test_exchange", :"x-delayed-message", arguments: args)
```

https://github.com/pma/amqp#types-of-arguments-and-headers
