### ISSUE TITLE
CHANNEL_ERROR - second 'channel.open' error

### ISSUE THREAD

**Issue by nulian** [pma/amqp#174]
Hey i'm trying to upgrade the amqp driver for improved handling of channel closure to stop leakage of that.
Using the AMQP.DirectConsumer for that but also have the same issue without it.

But when the process dies without cleanly closing the channel itself. And either a Process.link or DirectConsumer does that I get the following error below on a new open_channel call.
When the on_exit opens a new channel to delete remaining queues I get this second channel open error.

```
16:25:31.595 [error] GenServer Roger.AMQPClient terminating
** (stop) exited in: :gen_server.call(#PID<0.1132.0>, :open, 60000)
    ** (EXIT) shutdown: {:connection_closing, {:server_initiated_close, 504, "CHANNEL_ERROR - second 'channel.open' seen"}}
    (stdlib 3.13.2) gen_server.erl:246: :gen_server.call/3
    (amqp_client 3.8.9) /Users/petera/Sites/roger/deps/amqp_client/src/amqp_gen_connection.erl:55: :amqp_gen_connection.open_channel/3
    (amqp 1.6.0) lib/amqp/channel.ex:37: AMQP.Channel.do_open_channel/2
    (roger 2.4.2) lib/roger/amqp_client.ex:77: Roger.AMQPClient.handle_call/3
    (stdlib 3.13.2) gen_server.erl:706: :gen_server.try_handle_call/4
    (stdlib 3.13.2) gen_server.erl:735: :gen_server.handle_msg/6
    (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.1121.0>): {:open_channel, nil}
State: %Roger.AMQPClient.State{client_channel: %AMQP.Channel{conn: %AMQP.Connection{pid: #PID<0.753.0>}, custom_consumer: nil, pid: #PID<0.762.0>}, config: [host: "127.0.0.1", port: 5672, username: "user", password: "password", virtual_host: "/vhost"], connection: %AMQP.Connection{pid: #PID<0.753.0>}}
Client #PID<0.1121.0> is alive

    (stdlib 3.13.2) gen.erl:208: :gen.do_call/4
    (elixir 1.11.2) lib/gen_server.ex:1024: GenServer.call/3
    (roger 2.4.2) lib/roger/amqp_client.ex:24: Roger.AMQPClient.open_channel/1
    test/roger/consumer_test.exs:3: anonymous fn/0 in Roger.Partition.ConsumerTest.__ex_unit_setup_1/1
    (ex_unit 1.11.2) lib/ex_unit/on_exit_handler.ex:143: ExUnit.OnExitHandler.exec_callback/1
    (ex_unit 1.11.2) lib/ex_unit/on_exit_handler.ex:129: ExUnit.OnExitHandler.on_exit_runner_loop/0
```

**Comment by ono** [comment]
Hi 👋 

Could you share the test code that lets us reproduce the issue please? That will let us give you a right advise. Thanks!
